### ISSUE TITLE
Create invalidations

### ISSUE THREAD

**Issue by nathanbowser** [lpender/gulp-cloudfront-invalidate-aws-publish#16]
This recent commit https://github.com/lpender/gulp-cloudfront-invalidate-aws-publish/commit/0863582dea5bfba6f1fb6160da2171a7c7517135 is breaking our deployments. We fingerprint our assets, so when a new version is shipped, cloudfront doesn't appear to know there is a new file.

**Comment by lpender** [comment]
Thanks for the heads up. I'll take a look in a few days.

**Comment by nathanbowser** [comment]
Hi @lpender Curious if you had a chance to take a look? We've been using a modification that reverts the change in 0863582dea5bfba6f1fb6160da2171a7c7517135. I'm curious if you're planning on keeping that commit, if so our fork will need to be a bit more permanent.

**Comment by lpender** [comment]
Hey @nathanbowser just released `0.2.3` which reverts that commit. I'll look at alternatives at some point.

Thanks!
-Lee

**Comment by nathanbowser** [comment]
Thanks @lpender!
