### ISSUE TITLE
Invalidate root paths for index.html objects

### ISSUE THREAD

**Issue by levithomason** [lpender/gulp-cloudfront-invalidate-aws-publish#9]
When using CF in front of an S3 website, you can configure it such that `/foo/` resolves to `/foo/index.html`.  Currently, this plugin only invalidates the `/foo/index.html` object.  When users visit `/foo/` the old index.html is still served.  This is because the `/foo/` path is it's own object and also needs invalidated.

You can see this same issue outlined and fixed in the `s3_website` gem sometime ago [here](https://github.com/laurilehmijoki/s3_website/issues/29).

The solution is to invalidate the root path for an index.html if the `file.s3.path` is an index.html.  As with `s3_website` it would probably make sense to put this behind an option and document it.

If this is something you would merge, I'll make PR.  Please let me know.

**Comment by lpender** [comment]
Yes, I'll merge. Thanks!

**Comment by levithomason** [comment]
See #10
